    name: Generate Sitemap

    on:
      push:
        branches:
          - main # Or your default branch for GitHub Pages

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the repo
            uses: actions/checkout@v4
            with:
              fetch-depth: 0 # Required for accurate <lastmod> tags

          - name: generate-sitemap
            uses: cicirello/generate-sitemap@v1.10.4
            with:
              base-url: "https://cgdops.github.io/remembermeseries/" # Replace with your GitHub Pages URL

          - name: Commit and Push Sitemap
            run: |
              git config user.name github-actions[bot]
              git config user.email github-actions[bot]@users.noreply.github.com
              git add sitemap.xml
              git commit -m "Generate sitemap.xml" || echo "No changes to commit"
              git push
